apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}"
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "fullname" . }}"
      annotations:
        autonomy.io/devise: "true"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ required "An image repository is required!" .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: devise-example-client
              key: vaultToken
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
